# Adds sudo without password to user 'cloud1'
# (that was created by ssh public key added to vm)

- name: Add sudoers file
  ansible.builtin.copy:
    src: .
    dest: /etc/sudoers.d/cloud1
    mode: '440'
  become: true
# https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/copy_module.html