- name: Curl site (ignore SSL cert)
  uri:
    url: "https://{{ item.0 }}{{ item.1 }}"
    method: GET
    validate_certs: no
  register: curl_result
  failed_when: curl_result.status is defined and curl_result.status != 200
  loop: "{{ groups['cloud1hosts'] | product(['', '/phpmyadmin']) | list }}"