# ROLE: Checks
# Performs basic curls to ensure site is up and running correctly

- name: Curl site (ignore SSL cert)
  uri:
    url: "https://{{ ansible_default_ipv4.address }}{{ item }}"
    method: GET
    validate_certs: no
  register: curl_result
  failed_when: curl_result.status is defined and curl_result.status != 200
  loop:
    - ""
    - "/phpmyadmin"