- name: Sync files
  ansible.posix.synchronize:
    src: .
    dest: "{{ project_dir }}"
    archive: false    # (Disables) Mirrors the rsync archive flag, enables recursive, links, perms, times, owner, group flags, and -D.
    checksum: true    # Skip based on checksum, rather than mod-time & size;
    # delete: true      # Delete files in dest that do not exist (after transfer, not before) in the src path.
    recursive: true   # Recurse into directories.
    times: false      # (Do not) Preserve modification times.
    rsync_opts:
      - "--exclude=.env"
      - "--exclude=.vault_pass"
  register: sync_result
# https://docs.ansible.com/projects/ansible/latest/collections/ansible/posix/synchronize_module.html

- name: Add public IP as domain name in .env
  become: true
  ansible.builtin.lineinfile:
    path: "{{ project_dir }}/.env"
    regexp: '^DOMAIN_NAME='
    line: "DOMAIN_NAME={{ inventory_hostname }}"
# https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/lineinfile_module.html

- name: Set ownership
  become: true
  ansible.builtin.file:
    path: "{{ project_dir }}"
    owner: www-data
    group: www-data
    recurse: true