- name: Create secrets directory
  ansible.builtin.file:
    path: "{{ secrets_dir }}"
    state: directory
    mode: '0700'
  delegate_to: localhost
# server.key
- name: Generate private key for SSL
  community.crypto.openssl_privatekey:
    path: "{{ server_key_file }}"
    size: 2048
    type: RSA
  delegate_to: localhost
# server.crt
- name: Generate self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ server_crt_file }}"
    privatekey_path: "{{ server_key_file }}"
    provider: selfsigned
  delegate_to: localhost
# other secrets
- name: Generate persistent passwords
  ansible.builtin.set_fact:
    password: "{{ lookup('ansible.builtin.password', item, length=32) }}"
  loop:
    - "{{ blowfish_file }}"
    - "{{ db_pwd_file }}"
    - "{{ db_root_pwd_file }}"
    - "{{ wp_admin_pwd_file }}"