- name: Create secrets directory
  ansible.builtin.file:
    path: "{{ secrets_dir }}"
    state: directory
    mode: '0700'
  delegate_to: localhost

- name: Generate private key for SSL
  community.crypto.openssl_privatekey:
    path: "{{ server_key_file }}"
    size: 2048
    type: RSA
  delegate_to: localhost

- name: Read generated private key into vault variable
  ansible.builtin.slurp:
    src: "{{ server_key_file }}"
  register: ssl_key_content
  delegate_to: localhost

- name: Save private key content to vault file
  ansible.builtin.copy:
    content: "vault_ssl_private_key: \"{{ ssl_key_content.content | b64decode }}\""
    dest: "{{ secrets_dir }}/vault_ssl.yml"
    mode: '0600'
  delegate_to: localhost

- name: Encrypt SSL vault file
  ansible.builtin.command:
    cmd: ansible-vault encrypt {{ secrets_dir }}/vault_ssl.yml
  delegate_to: localhost

- name: Generate self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ server_crt_file }}"
    privatekey_path: "{{ server_key_file }}"
    provider: selfsigned
  delegate_to: localhost
