# ROLE: Setup
# Ensures target host’s SSH key is known before connecting
# If not yet in known_hosts
# temporarily disables strict host key checking to allow first connection

# Checks if target node is known by control node
- name: Check known_hosts for {{ inventory_hostname }}
  local_action: shell ssh-keygen -F {{ inventory_hostname }}
  register: is_known_host
  ignore_errors: true               # Continues even if target is not found in known_hosts
  changed_when: false               # Prevents the task from being marked as "changed"

# When (if) target node is not known by control node
# Omits key check to allow first connection
- name: Ignore host key for {{ inventory_hostname }} on first run
  when: is_known_host.rc != 0       # ssh-keygen did not find host
  set_fact:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

# Now, it is safe to gather facts
- name: Delayed gathering of facts
  setup:                            # Gathers system facts about the remote host